background:
  category: Background
  values:
    blue_bgr:
      name: Blue
      prob: 0.125
      src: img/backgrounds/blue.png
    green_bgr:
      name: Green
      prob: 0.125
      src: img/backgrounds/green.png
    grey_bgr:
      name: Grey
      prob: 0.125
      src: img/backgrounds/grey.png
    holographic_bgr:
      name: Holographic
      prob: 0.125
      src: img/backgrounds/holographic.png
    pink_bgr:
      name: Pink
      prob: 0.125
      src: img/backgrounds/pink.png
    purple_bgr:
      name: Purple
      prob: 0.125
      src: img/backgrounds/purple.png
    red_bgr:
      name: Red
      prob: 0.125
      src: img/backgrounds/red.png
    yellow_bgr:
      name: Yellow
      prob: 0.125
      src: img/backgrounds/yellow.png

face:
  category: Face
  values:
    tone_one:
      name: Tone One
      prob: 0.33
      src: img/faces/tone1.png
    tone_two:
      name: Tone Two
      prob: 0.33
      src: img/faces/tone2.png
    tone_three:
      name: Tone Three
      prob: 0.34
      src: img/faces/tone3.png

cloth:
  category: Cloth
  values:
    blue_clth:
      name: Blue
      prob: 0.25
      src: img/clothes/blue.png
    brown_clth:
      name: Brown
      prob: 0.25
      src: img/clothes/brown.png
    jacket_clth:
      name: Jacket
      prob: 0.25
      src: img/clothes/jacket.png
    transparent_clth:
      name: Transparent
      prob: 0.25
      src: img/clothes/transparent.png

eye:
  category: Eye
  values:
    right_eye:
      name: Right
      prob: 0.5
      src: img/eyes/eyeright.png
    left_eye:
      name: Left
      prob: 0.5
      src: img/eyes/eyeleft.png

nose:
  category: Nose
  values:
    downturned_nose:
      name: Downturned
      prob: 0.33
      src: img/noses/downturned.png
    upturned_nose:
      name: Upturned
      prob: 0.33
      src: img/noses/upturned.png
    prominent_nose:
      name: Prominent
      prob: 0.34
      src: img/noses/prominent.png

hair:
  category: Hair
  values:
    bob_hair:
      name: Bob
      prob: 0.2
      src: img/hairs/bob.png
    croppedcut_hair:
      name: Cropped Cut
      prob: 0.1
      src: img/hairs/croppedcut.png
    egirl_hair:
      name: E Girl
      prob: 0.1
      src: img/hairs/egirl.png
    hawk_hair:
      name: Hawk
      prob: 0.2
      src: img/hairs/hawk.png
    peak_hair:
      name: Peak
      prob: 0.2
      src: img/hairs/peak.png
    punk_hair:
      name: Punk
      prob: 0.1
      src: img/hairs/punk.png
    spike_hair:
      name: Spike
      prob: 0.1
      src: img/hairs/spike.png

mouth:
  category: Mouth
  values:
    one_mouth:
      name: Variant One
      prob: 0.33
      src: img/mouths/default.png
    two_mouth:
      name: Variant Two
      prob: 0.33
      src: img/mouths/variant2.png
    three_mouth:
      name: Variant Three
      prob: 0.33
      src: img/mouths/variant3.png
